---
- name: Install Prometheus and Grafana
  apt:
    name:
      - prometheus
      - grafana
    state: present
  become: yes
  tags: monitoring

- name: Ensure Prometheus is running
  service:
    name: prometheus
    state: started
    enabled: true
  become: yes
  tags: monitoring

- name: Ensure Grafana is running
  service:
    name: grafana-server
    state: started
    enabled: true
  become: yes
  tags: monitoring
