---
- name: Monitoring | Install Prometheus and Grafana
  ansible.builtin.dnf:
    name:
      - prometheus
      - grafana
    state: present

- name: Monitoring | Start and enable Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Monitoring | Start and enable Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
