---
- name: Install Postfix and Dovecot
  apt:
    name:
      - postfix
      - dovecot-imapd
    state: present
  become: yes
  tags: email

- name: Ensure Postfix is running
  service:
    name: postfix
    state: started
    enabled: true
  become: yes
  tags: email

- name: Ensure Dovecot is running
  service:
    name: dovecot
    state: started
    enabled: true
  become: yes
  tags: email
