---
- name: TLS | Install certbot
  ansible.builtin.dnf:
    name: certbot
    state: present

- name: TLS | Generate self-signed certificate for Apache
  ansible.builtin.command:
    cmd: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/selfsigned.key -out /etc/pki/tls/certs/selfsigned.crt -subj "/CN={{ hostname }}.{{ domain_name }}"
  args:
    creates: /etc/pki/tls/certs/selfsigned.crt

- name: TLS | Ensure Apache listens on 443
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "Listen 443"
    state: present
  notify: Restart httpd
