---
- name: Install BIND9
  apt:
    name: bind9
    state: present
  become: yes
  tags: dns

- name: Ensure BIND service is running
  service:
    name: bind9
    state: started
    enabled: true
  become: yes
  tags: dns
